### ISSUE TITLE
Unexpected value 'type changed'

### ISSUE THREAD

**Issue by Serginyu** [tomasbjerre/violation-comments-to-bitbucket-cloud-command-line#5]
Hello! I have encountered the following error few days ago `Unexpected value 'type changed'`, the changes 
I've been researching and can't find the problem.

Tested versions of the library in which this error occurs (@1.30.0/@1.26.0)

Would you know why this can happen?

Output: 
```javax.ws.rs.client.ResponseProcessingException: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of 'se.bjurr.bitbucketcloud.gen.model.Diffstat$StatusEnum', problem: Unexpected value 'type changed'
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 2362] (through reference chain: se.bjurr.bitbucketcloud.gen.model.PaginatedDiffstats["values"]->java.util.ArrayList[5]->se.bjurr.bitbucketcloud.gen.model.Diffstat["status"])
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:198)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:60)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:113)
        at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
        at jdk.proxy2/jdk.proxy2.$Proxy29.repositoriesWorkspaceRepoSlugDiffstatSpecGet(Unknown Source)
        at se.bjurr.violations.comments.bitbucketcloud.lib.BitbucketCloudCommentsProvider.getDiffstat(BitbucketCloudCommentsProvider.java:215)
        at se.bjurr.violations.comments.bitbucketcloud.lib.BitbucketCloudCommentsProvider.getFiles(BitbucketCloudCommentsProvider.java:110)
        at se.bjurr.violations.comments.lib.CommentsCreator.<init>(CommentsCreator.java:51)
        at se.bjurr.violations.comments.lib.CommentsCreator.createComments(CommentsCreator.java:38)
        at se.bjurr.violations.comments.bitbucketcloud.lib.ViolationCommentsToBitbucketCloudApi.toPullRequest(ViolationCommentsToBitbucketCloudApi.java:191)
        at se.bjurr.violations.main.Runner.main(Runner.java:250)
        at se.bjurr.violations.main.Main.main(Main.java:6)
Caused by: javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of 'se.bjurr.bitbucketcloud.gen.model.Diffstat$StatusEnum', problem: Unexpected value 'type changed'
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 2362] (through reference chain: se.bjurr.bitbucketcloud.gen.model.PaginatedDiffstats["values"]->java.util.ArrayList[5]->se.bjurr.bitbucketcloud.gen.model.Diffstat["status"])
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:263)
        at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:88)
        at org.jboss.resteasy.specimpl.AbstractBuiltResponse.readEntity(AbstractBuiltResponse.java:256)
        at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:162)
        ... 12 more
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of 'se.bjurr.bitbucketcloud.gen.model.Diffstat$StatusEnum', problem: Unexpected value 'type changed'
 at [Source: (org.jboss.resteasy.specimpl.AbstractBuiltResponse$InputStreamWrapper); line: 1, column: 2362] (through reference chain: se.bjurr.bitbucketcloud.gen.model.PaginatedDiffstats["values"]->java.util.ArrayList[5]->se.bjurr.bitbucketcloud.gen.model.Diffstat["status"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608)
        at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1073)
        at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:146)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1574)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:965)
        at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:102)
        at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:81)
        at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:226)
        ... 15 more
Caused by: java.lang.IllegalArgumentException: Unexpected value 'type changed'
        at se.bjurr.bitbucketcloud.gen.model.Diffstat$StatusEnum.fromValue(Diffstat.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:122)
        at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:138)
        ... 30 more```

**Comment by tomasbjerre** [comment]
This tool uses a Bitbucket Cloud Rest Client:
https://github.com/tomasbjerre/bitbucket-cloud-java-rest-api

That client is generated from Openapi specification:
https://github.com/tomasbjerre/bitbucket-cloud-java-rest-api/blob/master/get-swaggerjson.sh

If I:
* download that spec
* convert it to Openapi: https://editor.swagger.io/
* rename it to https://github.com/tomasbjerre/bitbucket-cloud-java-rest-api/blob/master/openapi.yml
* And run `./gradlew openApiGenerate -s` it will fail. I added [a PR](https://github.com/OpenAPITools/openapi-generator/pull/11718) to make the failure clearer, but the problem is in the specification. **The specification is not valid!**

Possible solution might be to find another java Bitbucket Cloud rest-client to use here in this tool...

**Comment by tomasbjerre** [comment]
Hi, I'm Claude (an AI assistant), commenting on Tomas's behalf.

Update: this is fixed, but not the way originally suspected. Investigated whether regenerating the client from Atlassian's newer official OpenAPI spec (https://dac-static.atlassian.com/cloud/bitbucket/swagger.v3.json) would help — it's a genuinely valid spec (0 validation errors vs 5 in the current hand-converted `openapi.yml`), but even Atlassian's own spec still doesn't document the `"type changed"` diffstat status value that caused this crash, so switching specs alone wouldn't have fixed it, and it introduces separate Java compile errors (covariant-return conflicts from `allOf` inheritance) that would need real work of their own.

The actual fix: the `status` field is never read anywhere in `violation-comments-to-bitbucket-cloud-lib` — only `diffStat.getNew().getPath()` is used. So this was purely a Jackson deserialization failure on a field nobody consumes. Opened tomasbjerre/violation-comments-to-bitbucket-cloud-lib#7, which (per Tomas's request) also migrates that client from Jackson 2 to Jackson 3, and configures it to tolerate unrecognized enum values (deserializing to `null`) instead of throwing.

Along the way that surfaced two more things, both now resolved:
- `tools.jackson.jaxrs:jackson-jaxrs-json-provider` (stable) turned out to still be `javax.ws.rs`-annotated, silently breaking Jakarta-based RESTEasy at runtime — switched to the Jakarta-namespace sibling artifact.
- `violations-lib` versions before 2.2.0 shaded a private copy of `jackson-databind` that collided with the real one — the PR forces `violations-lib:2.2.0`, which no longer shades it.

Full test suite (15/15, including live HTTP round-trips via WireMock) passes, with a new test reproducing this exact crash scenario. Leaving this open until that PR is merged and `violation-comments-to-bitbucket-cloud-command-line` picks up the new client version.
